export const RegistrationPageLocators = {
    signUpNameInputField: '[data-qa="signup-name"]',
    signUpEmailInputField: '[data-qa="signup-email"]',
    signUpButton: '[data-qa="signup-button"]',
    nameInputField: '#name',
    emailInputField: '#email',
    passwordInputField: '#password',
    genderRadioButton: (gender: string) => `#id_gender${gender}`,
    daysDropdown: '#days',
    monthDropdown: '#months',
    yearDropdown: '#years',
    newsLetterCheckbox: '#newsletter',
    receiveSpecialOffersFromOurPartnersCheckbox: '#optin',
    firstNameInputField: '#first_name',
    lastNameInputField: '#last_name',
    companyInputField: '#company',
    firstAddressInputField: '#address1',
    secondAddressInputField: '#address2',
    countryDropdown: '#country',
    stateInputField: '#state',
    cityInputField: '#city',
    zipCodeInputField: '#zipcode',
    mobileNumberInputField: '#mobile_number',
    createAccountButton: '[data-qa="create-account"]',
    containerSelector: '#form .container',
    accountCreatedText: '[data-qa="account-created"]',
    shopMenu: '.shop-menu.pull-right li',
    newUserSignUpTextXpathLocator: '//h2[contains(text(), "New User Signup!")]',
    enterAccountInformationTextXpathLocator: '//b[contains(text(), "Enter Account Information")]',
    continueButton: '[data-qa="continue-button"]',
    accountDeletedTextSelector: '[data-qa="account-deleted"]',
    loginEmailInputField: '[data-qa="login-email"]',
    loginPasswordInputField: '[data-qa="login-password"]',
    loginButton: '[data-qa="login-button"]'
}